name: Extraction
main: com.extraction.ExtractionPlugin
version: '1.0'
api: '1.21'
api-version: 1.21
commands:
  lootchestset:
    description: Setup or update a loot chest
    usage: /lootchestset
    permission: extraction.admin
  resetloot:
    description: Force reset all loot
    usage: /resetloot
    permission: extraction.admin
  stash:
    description: Open your personal stash
    usage: /stash
  extractpoint:
    description: Setup an extraction point
    usage: /extractpoint
    permission: extraction.admin
  setworld:
    description: Set extraction/lobby world
    usage: /setworld <extract|lobby> <World>
    permission: extraction.admin
  extractoutbanner:
    description: Set an extract out banner
    usage: /extractoutbanner
    permission: extraction.admin
  balance:
    description: Check money balance
    usage: /balance
  setmoney:
    description: Set a player's balance to a value or text (admin)
    usage: /setmoney <player> <amount>
    permission: extraction.admin
  givemoney:
    description: Add money to a player (admin)
    usage: /givemoney <player> <amount>
    permission: extraction.admin
  sell:
    description: Open the sell GUI
    usage: /sell
  value:
    description: Check the value of an item
    usage: /value
  setextracttopoint:
    description: Set an extract-to point (max 30)
    usage: /setextracttopoint
    permission: extraction.admin
  extractgive:
    description: Give special extraction items to players
    usage: /extractgive <player> <banner|flare|teleporter> [amount]
    permission: extraction.admin
  auction:
    description: Open the auction house
    usage: /auction [sell <price>|browse|my|collect]
  profile:
    description: View player profile and stats
    usage: /profile [player]
  wipe:
    description: Wipe all player data (admin only)
    usage: /wipe <player>
    permission: extraction.admin
  disableresourcepack:
    description: Toggle resource pack enforcement
    usage: /disableresourcepack [toggle]
    permission: extraction.resourcepack.manage
  trade:
    description: Send a money trade offer to a player
    usage: /trade <player>
  accepttrade:
    description: Accept a pending trade offer
    usage: /accepttrade
  declinetrade:
    description: Decline a pending trade offer
    usage: /declinetrade
  tempevent:
    description: Trigger temperature events
    usage: /tempevent <heatwave|cold|end>
    permission: extraction.admin
  claimdoor:
    description: Claim a door for protection
    usage: /claimdoor
  claimchest:
    description: Claim a chest or barrel for protection
    usage: /claimchest
  report:
    description: Report a player for misconduct
    usage: /report <player> <reason>
  setreporthook:
    description: Set the Discord webhook for reports
    usage: /setreporthook <webhook_url>
    permission: extraction.admin
  servermap:
    description: Get a clickable link to the server map
    usage: /servermap
  setservermap:
    description: Set the server map URL
    usage: /setservermap <url>
    permission: extraction.admin
  giverank:
    description: Give a rank to a player
    usage: /giverank <player> <rank>
  team:
    description: Manage teams
    usage: /team <create|invite|accept|leave|chat|stash>